### ISSUE TITLE
hdmi

### ISSUE THREAD

**Issue by cyb3rx7n** [wilsomwong/Asus-TUF-FX504GE-Hackintosh#1]
hey whats up bro the hdmi work ?

**Comment by wilsomwong** [comment]
HDMI port I haven't tested yet so I don't know it will work or not, but  I will notify you after I test later.

**Comment by cyb3rx7n** [comment]
can u check out and tell me the result

**Comment by wilsomwong** [comment]
Thanks for waiting for me to test. HDMI will work when you use my latest EFI (Open core 7.1 EFI), you can share your screen using your HDMI port now(Although when you connect your HDMI every time the monitor will flash green screen and return to normal). But unfortunately is HDMI sound cannot work, I'll gonna fix the HDMI sound and I'll update my Github soon.

**Comment by wilsomwong** [comment]
Hope that this time HDMI working for you. If any issue happens, welcome to chat again.

**Comment by cyb3rx7n** [comment]
maybe some of thoses link can help u to start

https://github.com/zzNuAzz/Hackintosh_ASUS_TUF_FX504/issues/3

https://github.com/felixyonathan/Asus-TUF-FX504GE-OpenCore/issues/1

**Comment by wilsomwong** [comment]
Ohhh .. Thanks for giving me some examples, I'll chat here when I fixed the problem.

**Comment by cyb3rx7n** [comment]
> Ohhh .. Thanks for giving me some examples, I'll chat here when I fixed the problem.

You are welcome bro just let me know if anything work with u about hdmi

**Comment by wilsomwong** [comment]
Sorry for waiting a long time, I have great news is I make the HDMI sound working but the bad news is HDMI video becomes not too stable (HDMI video something blinks the screen and connects back to repeatedly but something work great). I gonna fix the bug but now just already complete to use if you want to use it (I'll call this is an alpha version, so don't put too many expectations lol). Thanks for giving for me and giving some examples for me.

Config.plist file ALREADY UPDATE IN OPENCORE 7.1 EFI FILES.

** Notice: I add some new text into it, so please download and place the text in your text file and replace your config. plist to prevent error. You can see in the releases sections what kext I add.

**Comment by cyb3rx7n** [comment]
really for now im not have mac os on that laptop just i have win 10 
maybe some ti,e later not now 
i will check it out and test that thing i will see if work to me too or not 
thanks you mac i appreciiate that

**Comment by wilsomwong** [comment]
You are welcome .

**Comment by cyb3rx7n** [comment]
bro did u have whatsapp ? or facebook that i can call you ?
im going to install that system 🤣🤣 i think im going to be crazy

**Comment by wilsomwong** [comment]
hahaha I agree with you. Also, I always afraid my laptop will break after doing Hackintosh. You can chat with me on Gitter and sorry that I can't give my WhatsApp and Facebook because these platforms are my personal account and not open to anyone.

Gitter Chat :
https://gitter.im/Hackintosh-for-Asus-TUF-FX504/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by cyb3rx7n** [comment]
Nothing going to broke your laptop except dgpu if u going to play around vbois of dgpu of course will that happen it that end im now have win 11 and linux there tutorial about install nvidia drive on linux and it's work here the link : https://forums.kali.org/showthread.php?35748-TUTORIAL-Installing-official-NVIDIA-driver-in-Optimus-laptop
