### ISSUE TITLE
Continue

### ISSUE THREAD

**Issue by weijun2922** [wilsomwong/Asus-TUF-FX504GE-Hackintosh#5]
Looking forward to next update!
Thank you!

**Comment by wilsomwong** [comment]
Thanks for supporting, I will update if any bigger updates or problems are fixed and hope you can enjoy Hackintosh too.

**Comment by wilsomwong** [comment]
Okay I think I have a mistake, I update it through the developer version from Big Sur to Monterey with some tricks ( I did not buy developer ), after that I realize that I can't update anymore it is stuck at 12.0  I think this is the problem that unable to receive an update any more ... Another problem is my EFI is like fragile glass when I just change the kext and it will be stuck on the progress bar. so I have to change to the window and change the kext to test, but my HDD which mean the windows system disk have some problem recently, It has boot up after 5 min to the windows system and I don't use that laptop often so I did not decide to change the HDD...  You can try searching the internet for the solution and sorry for being unable to solve the problem ... Btw If any solution I found, I will update my GitHub.

**Comment by wilsomwong** [comment]
Thanks for waiting, the latest EFI (Ventura EFI) already fix this problem. So pls download the latest EFI for further updates, and the old EFI can throw into the trash because there have some bugs that I don't know have to fix, I already fix like almost one year.
